//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace n_ate.Swagger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("n_ate.Swagger.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .stack-trace .stack-trace-line {
        ///    margin: 0 0 0 3em;
        ///    white-space: nowrap;
        ///}
        ///
        ///.stack-trace .quote-start {
        ///    display: inline;
        ///    margin: 0;
        ///}
        ///
        ///.popup-notice.container {
        ///    background: #FEE;
        ///    border: 3px solid rgb(255, 0, 0);
        ///    border-radius: 12px;
        ///    box-shadow: rgba(0,0,0,0.7) 5px 3px 14px;
        ///    font-family: Arial;
        ///    padding: 0 10px;
        ///    position: absolute;
        ///    right: 190px; /*unknown-browsers, not listed below*/
        ///    text-align: center;
        ///    top: 0;
        ///    width: 240px;
        ///}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swagger_extender_css {
            get {
                return ResourceManager.GetString("swagger_extender_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.swaggerExtender = (function () {
        ///    console.log(&apos;swagger-extentender.js loaded.&apos;);
        ///
        ///    function whenReady(name, readyFunction, callbackFunction, maxChecks) {
        ///        if (maxChecks == 0) console.log(&apos;whenReady function reached the maximum number of checks. Name: &apos; + name);
        ///        else if (readyFunction()) callbackFunction();
        ///        else setTimeout(() =&gt; { whenReady(name, readyFunction, callbackFunction, maxChecks--); }, 50);
        ///    }
        ///
        ///    whenReady(
        ///        &quot;when page loaded, trigger defini [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swagger_extender_js {
            get {
                return ResourceManager.GetString("swagger_extender_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///    console.log(&apos;swagger-operations-filter.js loaded.&apos;);
        ///
        ///    swaggerExtender.registerDefinitionLoadedListener(injectOperationsFilterUI);
        ///
        ///    function initRouteData(callback) {
        ///        let getRouteData = () =&gt; {
        ///            let results = [];
        ///            results.maxPathSegments = 0;
        ///            let opSections = Array.from(document.querySelectorAll(&quot;.opblock-tag-section&quot;));
        ///            for (let i = 0; i &lt; opSections.length; i++) {
        ///                let sectionData = { section: opSecti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swagger_operations_filter_js {
            get {
                return ResourceManager.GetString("swagger_operations_filter_js", resourceCulture);
            }
        }
    }
}
